# Generated by Django 3.1.1 on 2021-02-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20210213_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
    ]
