# Generated by Django 3.1.1 on 2021-03-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_folder_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=255)),
                ('folder_name', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
