# Generated by Django 3.1.8 on 2021-04-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_uploaded_folder_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploaded_folder_details',
        ),
    ]
