# Generated by Django 3.0.9 on 2020-10-12 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Bank_master',
            fields=[
                ('bank_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('bank_micr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_master_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_master_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
