# Generated by Django 3.1.1 on 2021-02-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bank_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='entity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='entity_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='source_of_trans',
            field=models.CharField(blank=255, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='sub_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
