# Generated by Django 3.1.1 on 2021-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20210226_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='debit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
