# Generated by Django 3.1.1 on 2021-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20210226_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='transaction_type',
            field=models.CharField(blank=255, max_length=255, null=True),
        ),
    ]
