# Generated by Django 3.0.9 on 2020-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pan',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
