# Generated by Django 3.0.9 on 2020-10-22 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.CharField(blank=True, max_length=255)),
                ('name_of_deductor', models.CharField(blank=True, max_length=255)),
                ('number_of_transactions', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.CharField(blank=True, max_length=255)),
                ('deal_id', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table5_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table5_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=255)),
                ('k194', models.CharField(blank=True, max_length=255)),
                ('betting', models.CharField(blank=True, max_length=255)),
                ('collection_at_source', models.CharField(blank=True, max_length=255)),
                ('income_from_abroad', models.CharField(blank=True, max_length=255)),
                ('income_from_commission', models.CharField(blank=True, max_length=255)),
                ('income_from_contracting', models.CharField(blank=True, max_length=255)),
                ('income_from_tech_prof_services', models.CharField(blank=True, max_length=255)),
                ('orignal_investment_principal_withdrawal', models.CharField(blank=True, max_length=255)),
                ('rent', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('sale_of_property', models.CharField(blank=True, max_length=255)),
                ('deal_id', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table4_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table4_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.CharField(blank=True, max_length=255)),
                ('measures', models.CharField(blank=True, max_length=255)),
                ('january', models.CharField(blank=True, max_length=255)),
                ('february', models.CharField(blank=True, max_length=255)),
                ('march', models.CharField(blank=True, max_length=255)),
                ('april', models.CharField(blank=True, max_length=255)),
                ('may', models.CharField(blank=True, max_length=255)),
                ('june', models.CharField(blank=True, max_length=255)),
                ('july', models.CharField(blank=True, max_length=255)),
                ('august', models.CharField(blank=True, max_length=255)),
                ('september', models.CharField(blank=True, max_length=255)),
                ('october', models.CharField(blank=True, max_length=255)),
                ('november', models.CharField(blank=True, max_length=255)),
                ('december', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('deal_id', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table3_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table3_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.CharField(blank=True, max_length=255)),
                ('gross_income', models.CharField(blank=True, max_length=255)),
                ('average_monthly_gross_income', models.CharField(blank=True, max_length=255)),
                ('taxable_income', models.CharField(blank=True, max_length=255)),
                ('hra', models.CharField(blank=True, max_length=255)),
                ('rent_income', models.CharField(blank=True, max_length=255)),
                ('tax_default_found', models.CharField(blank=True, max_length=255)),
                ('ccc80', models.CharField(blank=True, max_length=255)),
                ('c80', models.CharField(blank=True, max_length=255)),
                ('d80', models.CharField(blank=True, max_length=255)),
                ('other_income_under_sec_192_2b', models.CharField(blank=True, max_length=255)),
                ('other_deductions', models.CharField(blank=True, max_length=255)),
                ('total_deductions', models.CharField(blank=True, max_length=255)),
                ('deal_id', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table1_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table1_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
