from django.db import models
from django.contrib.auth.models import User


class Itrv(models.Model):
    assessment_year = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    pan = models.CharField(max_length=255, blank=True, null=True)
    town_city_district_state = models.CharField(max_length=255, blank=True, null=True)
    pin_code = models.CharField(max_length=255, blank=True, null=True)
    efiling_acknowledgement_number = models.CharField(max_length=255, blank=True, null=True)
    form_no = models.CharField(max_length=255, blank=True, null=True)
    date_of_itr_filed = models.CharField(max_length=255, blank=True, null=True)
    gross_total_income = models.CharField(max_length=255, blank=True, null=True)
    deductions_under_chapter_vi_a = models.CharField(max_length=255, blank=True, null=True)
    total_income = models.CharField(max_length=255, blank=True, null=True)
    total_income_deemed_total_income_under_amt_mat = models.CharField(max_length=255, blank=True, null=True)
    total_income_current_year_loss = models.CharField(max_length=255, blank=True, null=True)
    net_tax_payable = models.CharField(max_length=255, blank=True, null=True)
    interest_and_fee_payable = models.CharField(max_length=255, blank=True, null=True)
    total_tax_interest_and_fee_payable = models.CharField(max_length=255, blank=True, null=True)
    taxes_paid_advance_tax = models.CharField(max_length=255, blank=True, null=True)
    taxes_paid_tds = models.CharField(max_length=255, blank=True, null=True)
    taxes_paid_tcs = models.CharField(max_length=255, blank=True, null=True)
    taxes_paid_self_assessment_tax = models.CharField(max_length=255, blank=True, null=True)
    taxes_paid_total_taxes_paid = models.CharField(max_length=255, blank=True, null=True)
    tax_payable = models.CharField(max_length=255, blank=True, null=True)
    refund = models.CharField(max_length=255, blank=True, null=True)
    deal_id = models.CharField(max_length=255, blank=True)
    customer_id = models.CharField(max_length=255, blank=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, related_name="iv_created_by")
    creation_time = models.DateTimeField(auto_now_add=True)
    last_modified_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, related_name="iv_last_modified_by")
    last_modification_time = models.DateTimeField(auto_now=True)
    image_name = models.CharField(max_length=255, blank=True)
