# Generated by Django 3.0.9 on 2020-10-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form16', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
