# Generated by Django 3.1.1 on 2021-02-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_1',
        ),
    ]
