# Generated by Django 3.0.9 on 2020-10-01 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhaar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('yob', models.CharField(blank=True, max_length=50)),
                ('gname', models.CharField(blank=True, max_length=255)),
                ('house', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('lm', models.CharField(blank=True, max_length=255)),
                ('vtc', models.CharField(blank=True, max_length=255)),
                ('po', models.CharField(blank=True, max_length=255)),
                ('dist', models.CharField(blank=True, max_length=255)),
                ('subdist', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('pc', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=255)),
                ('image_data', models.BinaryField()),
                ('deal_id', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aadhaar_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aadhaar_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
