# Generated by Django 3.0.9 on 2020-10-01 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itrv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pan', models.CharField(blank=True, max_length=255, null=True)),
                ('town_city_district_state', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=255, null=True)),
                ('efiling_acknowledgement_number', models.CharField(blank=True, max_length=255, null=True)),
                ('form_no', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_itr_filed', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_total_income', models.CharField(blank=True, max_length=255, null=True)),
                ('deductions_under_chapter_vi_a', models.CharField(blank=True, max_length=255, null=True)),
                ('total_income', models.CharField(blank=True, max_length=255, null=True)),
                ('total_income_deemed_total_income_under_amt_mat', models.CharField(blank=True, max_length=255, null=True)),
                ('total_income_current_year_loss', models.CharField(blank=True, max_length=255, null=True)),
                ('net_tax_payable', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_and_fee_payable', models.CharField(blank=True, max_length=255, null=True)),
                ('total_tax_interest_and_fee_payable', models.CharField(blank=True, max_length=255, null=True)),
                ('taxes_paid_advance_tax', models.CharField(blank=True, max_length=255, null=True)),
                ('taxes_paid_tds', models.CharField(blank=True, max_length=255, null=True)),
                ('taxes_paid_tcs', models.CharField(blank=True, max_length=255, null=True)),
                ('taxes_paid_self_assessment_tax', models.CharField(blank=True, max_length=255, null=True)),
                ('taxes_paid_total_taxes_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_payable', models.CharField(blank=True, max_length=255, null=True)),
                ('refund', models.CharField(blank=True, max_length=255, null=True)),
                ('deal_id', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iv_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iv_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
